### Test API

GET http://localhost:6688

### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Alice Chen",
    "workspace": "acme",
    "email": "alice@acme.org",
    "password": "123456"
}

### signup user
POST http://localhost:6688/api/signup
Content-Type: application/json

{
    "fullname": "Jason Chen",
    "workspace": "acme",
    "email": "Jason@acme.org",
    "password": "123456"
}

### signin user (invalid)

POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "tchen@acme.org",
    "password": "123456"
}



### signin user (valid)
# @name signin
POST http://localhost:6688/api/signin
Content-Type: application/json

{
    "email": "alice@acme.org",
    "password": "123456"
}

@token = {{signin.response.body.token}}

### get chat list
GET http://localhost:6688/api/chats
Authorization: Bearer {{token}}

### create chat
POST http://localhost:6688/api/chats
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "acme",
    "members": [1, 2],
    "public": false
}

### get user list
GET http://localhost:6688/api/users
Authorization: Bearer {{token}}

### upload files
POST http://localhost:6688/api/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; filename="xdiff.png"
Content-Type: application/octet-stream

< /Users/macworks/Desktop/xdiff.png
--MyBoundary
Content-Disposition: form-data; filename="hello.txt"
Content-Type: text/plain

Hello, World!
--MyBoundary--

### get files
GET http://localhost:6688/api/files/1/b91/7b3/65ead503469b48b2cd94fda296103ddd63.png
Authorization: Bearer {{token}}

### get txt files
GET http://localhost:6688/api/files/1/0a0/a9f/2a6772942557ab5355d76af442f8f65e01.txt
Authorization: Bearer {{token}}

### send a message
POST http://localhost:6688/api/chats/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Hello, World!",
    "files": []
}

### get messages
GET http://localhost:6688/api/chats/1/messages?limit=6&last_id=5
Authorization: Bearer {{token}}
